server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Oakleaf?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
  resources:
    static-locations: classpath:/templates  #访问静态页面
  thymeleaf:
    prefix: classpath:/templates/
    mode: LEGACYHTML5
    cache: false
    encoding: UTF-8
    #     新版本不支持content-type: text/html，故新写法
    servlet:
      content-type: text/html
  http:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
swagger:
  enable: true


